### ISSUE TITLE
Upgrade app to Ember 3.21 (Part 2 of 2)

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/cli-guides#198]
## Problem

~~Once #197 has been completed and merged, we can leverage `npm-run-all` to parallelize lints and tests.~~

After talking to @takshch, I think we can solve this issue in a slightly different manner. I've updated the TODOs below.

### Part 2. Update CI

- [ ] Install `npm-run-all`.

    ```bash
    npm install npm-run-all --save-dev
    ```

- [ ] Uninstall `ember-cli-template-lint` and `ember-cli-eslint`. Afterwards, install `ember-template-lint` and `eslint`.

   ```bash
   npm uninstall ember-cli-template-lint ember-cli-eslint
   npm install --save-dev ember-template-lint eslint
   ```

   If you run `npm run lint:hbs` or `npm run lint:js`, all lint checks should continue to pass.

- [ ] In `package.json`, create a `lint` script and update the `test` script to run tasks in parallel:

    ```json
    {
      "scripts": {
        "build": "ember build --environment=production",
        "lint": "npm-run-all --aggregate-output --continue-on-error --parallel lint:*",
        "lint:alex": "alex .",
        "lint:hbs": "ember-template-lint .",
        "lint:js": "eslint .",
        "lint:md": "remark . --frail",
        "start": "ember serve",
        "test": "npm-run-all --aggregate-output --continue-on-error --parallel test:*",
        "test:ember": "ember test",
        "test:node": "mocha node-tests"
      }
    }
    ```

- [ ] Simplify `.travis.yml` (CI script) to run `npm run lint`. Push a commit to check that the CI continues to pass.

    ```yaml
    # Before
    script:
      - set -o errexit
      - npm run lint:md
      - npm run lint:alex
      - npm run lint:hbs
      - npm run lint:js
      - npm test

    # After
    script:
      - set -o errexit
      - npm run lint
      - npm run test
    ```
